let allData=[];const rows=document.getElementById('reservationRows'),empty=document.getElementById('emptyState'),search=document.getElementById('searchInput'),statusFilter=document.getElementById('statusFilter'),dateFilter=document.getElementById('dateFilter');
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let unsubscribeData=null;
function showApp(user){document.getElementById('loginGate').hidden=true;document.getElementById('adminApp').hidden=false;const badge=document.getElementById('storageBadge');badge.textContent=`${LuaDataService.mode==='firebase'?'FIREBASE ONLINE':'LOCAL DEMO'} · ${LuaAuthService.mode==='firebase'?'AUTH':'DEMO LOGIN'}`;document.getElementById('modeNote').textContent=LuaDataService.mode==='firebase'?`온라인 저장 활성화. 로그인 계정: ${user?.email||'-'}`:'현재 이 브라우저에만 저장되는 데모 모드입니다. 실제 배포 전 Firebase Auth와 Firestore를 설정하세요.';if(!unsubscribeData)unsubscribeData=LuaDataService.subscribe(d=>{allData=d;render()})}
function showLogin(){document.getElementById('loginGate').hidden=false;document.getElementById('adminApp').hidden=true;if(unsubscribeData){unsubscribeData();unsubscribeData=null}}
document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();const error=document.getElementById('loginError');error.style.display='none';try{await LuaAuthService.login(document.getElementById('adminEmail')?.value.trim(),document.getElementById('adminPassword').value)}catch(err){error.textContent=LuaAuthService.mode==='firebase'?'로그인에 실패했습니다. 이메일과 비밀번호를 확인하세요.':'데모 비밀번호가 올바르지 않습니다.';error.style.display='block'}};
document.getElementById('logoutBtn').onclick=()=>LuaAuthService.logout();
function render(){let data=[...allData];const q=search.value.trim().toLowerCase();if(q)data=data.filter(r=>[r.id,r.name,r.phone].some(v=>(v||'').toLowerCase().includes(q)));if(statusFilter.value)data=data.filter(r=>r.status===statusFilter.value);if(dateFilter.value)data=data.filter(r=>r.date===dateFilter.value);rows.innerHTML=data.map(r=>`<tr><td><b>${esc(r.date)}</b><br>${esc(r.time)}<small>${esc(r.id)}</small></td><td>${esc(r.name)}<br><a href="tel:${esc(r.phone)}">${esc(r.phone)}</a>${r.memo?`<small>${esc(r.memo)}</small>`:''}</td><td>${esc(r.purpose)}</td><td>${esc(r.weddingDate||'-')}</td><td><select class="status-select" data-id="${esc(r.id)}"><option ${r.status==='신청'?'selected':''}>신청</option><option ${r.status==='확정'?'selected':''}>확정</option><option ${r.status==='완료'?'selected':''}>완료</option><option ${r.status==='취소'?'selected':''}>취소</option></select></td><td><button class="delete-btn" data-id="${esc(r.id)}">삭제</button></td></tr>`).join('');empty.style.display=data.length?'none':'block';document.querySelectorAll('.status-select').forEach(el=>el.onchange=()=>LuaDataService.update(el.dataset.id,{status:el.value}));document.querySelectorAll('.delete-btn').forEach(el=>el.onclick=async()=>{if(confirm('이 예약을 삭제할까요?'))await LuaDataService.remove(el.dataset.id)});updateStats()}
function updateStats(){const today=new Date().toISOString().slice(0,10);document.getElementById('totalCount').textContent=allData.length;document.getElementById('pendingCount').textContent=allData.filter(r=>r.status==='신청').length;document.getElementById('confirmedCount').textContent=allData.filter(r=>r.status==='확정').length;document.getElementById('todayCount').textContent=allData.filter(r=>r.date===today&&r.status!=='취소').length}
function csv(){const head=['예약번호','신청일','예약일','시간','상태','이름','연락처','방문목적','예식일','요청사항'];const lines=[head,...allData.map(r=>[r.id,r.createdAt,r.date,r.time,r.status,r.name,r.phone,r.purpose,r.weddingDate,r.memo])].map(row=>row.map(v=>'"'+String(v||'').replaceAll('"','""')+'"').join(','));const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`lua-bride-reservations-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
async function seed(){const now=new Date(),day=n=>{const d=new Date(now);d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};for(const s of [{id:'LB-SAMPLE01',createdAt:new Date().toISOString(),date:day(1),time:'11:00',purpose:'첫 상담',name:'김하늘',phone:'010-1234-5678',weddingDate:day(120),memo:'A라인 선호',status:'신청'},{id:'LB-SAMPLE02',createdAt:new Date().toISOString(),date:day(2),time:'15:00',purpose:'드레스 피팅',name:'박서윤',phone:'010-9876-5432',weddingDate:day(160),memo:'호텔 웨딩',status:'확정'}]){if(!allData.some(x=>x.id===s.id))await LuaDataService.add(s)}}
[search,statusFilter,dateFilter].forEach(el=>el.addEventListener('input',render));document.getElementById('clearFilter').onclick=()=>{search.value='';statusFilter.value='';dateFilter.value='';render()};document.getElementById('exportBtn').onclick=csv;document.getElementById('seedBtn').onclick=seed;LuaAuthService.onChange(user=>user?showApp(user):showLogin());
